services:
  - type: web
    name: literal-blog
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn literal_blog.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
